apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhook-proxy
  labels:
    app: webhook-proxy
spec:
  selector:
    matchLabels:
      app: webhook-proxy
  template:
    metadata:
      labels:
        app: webhook-proxy
    spec:
      serviceAccountName: webhook-proxy
      containers:
        - name: webhook-proxy
          image: ghcr.io/ahanafy/webhook-proxy:v1.2.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: TAG_DELIMITER
              value: ":"
            - name: SLEUTH_ENVIRONMENT
              value: "defaultenvironment"
            - name: SLEUTH_ORG_SLUG
              value: "DEFAULTORGSLUG"
          envFrom:
            - secretRef:
                name: sleuth
          resources:
            limits:
              cpu: 300m
              memory: 200Mi
            requests:
              cpu: 200m
              memory: 100Mi
